[compiler.solc]
include_paths = ["lib"]
exclude_paths = [
    "script",
    "venv",
    "node_modules",
    ".venv",
    "test",
    ".certora_internal",
]
remappings = [
"forge-std/=lib/forge-std/src/",
"erc4626-tests/=lib/openzeppelin-contracts-upgradeable/lib/erc4626-tests/",
"@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
"@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
"openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/",
"openzeppelin-contracts/=lib/openzeppelin-contracts/",
"@uniswap/v2-core/=lib/v2-core/",
"@uniswap/v2-periphery/=lib/v2-periphery/",
"@uniswap/v3-core/=lib/v3-core/",
"@uniswap/v3-periphery/=lib/v3-periphery/",
"@safe-global/safe-smart-account/=lib/safe-smart-account/",
"murky/=lib/murky/src/",
"safe-smart-account/=lib/safe-smart-account/",
"solady/=lib/solady/src/",
"solmate/=lib/solmate/src/",
"permit2/=lib/permit2/src/",
"ds-test/=lib/solmate/lib/ds-test/src/",
"forge-gas-snapshot/=lib/permit2/lib/forge-gas-snapshot/src/",
"halmos-cheatcodes/=lib/openzeppelin-contracts-upgradeable/lib/halmos-cheatcodes/src/",
"multicall/=lib/multicall/src/",
"v2-core/=lib/v2-core/contracts/",
"v2-periphery/=lib/v2-periphery/contracts/",
"v3-core/=lib/v3-core/contracts/",
"v3-periphery/=lib/v3-periphery/contracts/",
]
via_IR = false

[compiler.solc.optimizer]
enabled = true
runs = 200

[compiler.solc.metadata]
append_CBOR = true
use_literal_content = false
bytecode_hash = "none"

[detectors]
exclude = []
ignore_paths = ["test", "venv", ".venv"]
exclude_paths = ["lib", "script", "venv", "node_modules", ".venv", "test"]

[testing]
cmd = "anvil"

[testing.anvil]
cmd_args = "--prune-history 100 --transaction-block-keeper 10 --steps-tracing --silent"

[testing.ganache]
cmd_args = "-k istanbul -q"

[testing.hardhat]
cmd_args = ""
